### ISSUE TITLE
Event Handler + Chat Response

### ISSUE THREAD

**Issue by justindowning** [atmos/hubot-deploy-heroku#9]
Hello! I'm trying to add the event handler for the `github_deployment_event` and having a bit of trouble. I have a GH webhook setup to POST to my hosted hubot on Heroku with Deployment and Deployment Status events. Now, I want to kick of a deployment on Heroku and report that status back in chat + GH deployments API.

Here's what I have so far (and it's not working):

```
HerokuDeployment = require("hubot-deploy-heroku")
robot.on "github_deployment_event", (deployment) ->
  robot.logger.info JSON.stringify(deployment)
  try
    heroku_deployment = new HerokuDeployment(deployment)
    heroku_deployment.run (responseMessage) ->
      msg.reply responseMessage if responseMessage?
  catch err
    robot.logger.info "Failed to deploy to Heroku: #{err}"
```

log shows:

```
2016-03-04T03:53:05.063084+00:00 app[web.1]: [Fri Mar 04 2016 03:53:05 GMT+0000 (UTC)] INFO Failed to deploy to Heroku: TypeError: Object #<Deployment> has no method 'loadFile'
```

My setup is hubot hosted on Heroku with `hubot-deploy` and `hubot-deploy-heroku` (no Heaven). I setup the GH and Heroku tokens via Slack PM to the bot user. I am trying to get deploys to perform like your Slack screenshot:
![heroku deploy](https://camo.githubusercontent.com/a2328722b0e13c9b2a7ffe9b55225a00c550f9c6/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f33382f323333313133372f37373033366566382d613434342d313165332d393766362d3638646162363937356565622e6a7067) 
but my `hubot deploy app to env` command produces no feedback. GH creates the deployment and sends the result back to Hubot though.

Thanks in advance for the help!

**Comment by justindowning** [comment]
Hi @atmos! Would you be able to lend some direction for me here? :bow:

**Comment by atmos** [comment]
@justindowning What chat service are you running on?

**Comment by justindowning** [comment]
Slack. I _think_ I may have figured this out though. I can PR a `docs/` addition if you think it would be useful for others.

```
HubotDeployHeroku = require("hubot-deploy-heroku/src/helpers")
HerokuDeployment = HubotDeployHeroku.Deployment
robot.on "github_deployment_event", (deployment) ->
  user = robot.brain.userForName deployment.payload.deployment.payload.notify.user_name
  githubToken = robot.vault.forUser(user).get("hubot-deploy-github-secret")
  herokuToken = robot.vault.forUser(user).get("hubot-deploy-heroku-secret")

  try
    heroku_deployment = new HerokuDeployment(deployment, herokuToken, githubToken, robot.logger)
    heroku_deployment.run (responseMessage) ->
      msg.send responseMessage if responseMessage?
  catch err
    robot.logger.info "Failed to deploy to Heroku: #{err}"
```

**Comment by atmos** [comment]
@justindowning Do you use the heroku pipelines feature? I've started building all of the apps.json information for heroku apps programmatically from the heroku api. It's coming together as a [slash-heroku](https://github.com/atmos/slash-heroku) but needs a few more days.

Essentially slack users should be getting a very easy way to get hubot-deploy-style behavior without having to have a hubot at all. They just need to setup their pipelines.
